### PR TITLE
Sub-URI support

### LINKED ISSUE #934: Under docker, avatars don't seem to load
Seems to be something to do with Rails serving static assets in `production` mode. The env var `RAILS_SERVE_STATIC_FILES` controls this behaviour. It may have been that this was defaulting to "true" prior to the Rails 6 changes.

This also indicates that there is something potentially wrong with the nginx config, since the request should not be getting to the app server in the first place - nginx should be serving everything under `/public`

### PR DESCRIPTION
**Pull request by fbacall**
Docker changes to allow nginx to serve static files when running with a sub-URI.

Lots of changes to how SEEK generates URLs to ensure the sub-URI is respected.

Fixes #934, #938, #940, #941

### CODE REVIEW

File: app/controllers/culture_growth_types_controller.rb [hunk 1]
```diff
@@ -0,0 +1,16 @@
+class CultureGrowthTypesController < ApplicationController
```
Comment (stuzart) [inline app/controllers/culture_growth_types_controller.rb:1]: I don't see where this is need or used, other than the routes ??

Comment (stuzart) [reply app/controllers/culture_growth_types_controller.rb:1]: is it to allow polymorphic_url to work for all cases in the rdf generation ?

File: vendor/assets/stylesheets/jstree.scss [hunk 2]
```diff
@@ -403,7 +403,7 @@
 }
 .jstree-default .jstree-node,
 .jstree-default .jstree-icon {
-  background-image: url("32px.png");
+  background-image: url(image-path("32px.png"));
```
Comment (stuzart) [inline vendor/assets/stylesheets/jstree.scss:406]: since this is editing a `vendor/assets` can it be moved to `app/assets` ?

File: app/controllers/culture_growth_types_controller.rb (hunk 1 above)
Comment (fbacall) [reply app/controllers/culture_growth_types_controller.rb:1]: Yes exactly

File: vendor/assets/stylesheets/jstree.scss (hunk 2 above)
Comment (fbacall) [reply vendor/assets/stylesheets/jstree.scss:406]: Hmm, maybe. I didn't really like the solution of editing the CSS, but couldn't find any other way around it.

I got the idea from https://makandracards.com/makandra/29567-managing-vendor-libraries-with-the-rails-asset-pipeline#section-fixing-font-paths

I did wonder if there's a way to automatically do this as part of the asset-pipeline compilation, or how it works for the old rails-assets gems

Comment (stuzart) [reply vendor/assets/stylesheets/jstree.scss:406]: actually, there are plenty of other cases where files here have been edited
