### PR TITLE
Sitemaps

### LINKED ISSUE #1250: Generate Sitemap for list of public content
**Describe the bug**
Programmatic clients such as search engines and FAIR clients have no way to iterate all the content of WorkflowHub or to see when some of the assets may have been updated since last visit.

**Additional context**

[Sitemaps](https://www.sitemaps.org/protocol.html) is a method promoted by search engines that simply list pages and their last modification date. It is possible to have nested sitemaps, e.g. TeSS does it like this https://tess.elixir-europe.org/sitemap.xml per asset type + other pages.

**Other alternatives**

* Each asset collection page e.g. https://workflowhub.eu/workflows could use a schema.org type like https://workflowhub.eu/workflows -- unsure how they will be listed under https://workflowhub.eu/
* [OAI-PMH](https://www.openarchives.org/pmh/) is a classic used by harvesters like OpenAIRE and exposed by repositories like Zenodo
* [SWORD v3](https://sword.cottagelabs.com/swordv3/) is a modern alternative to the above that supports metadata and write operations. 
* .. I'm sure there are many more

### PR DESCRIPTION
**Pull request by fherreazcue**
Adds sitemaps using sitemap_generator gem.

Sitemaps are grouped by type, and only publicly visible items are added.

Resolves #1250

### CODE REVIEW

File: config/sitemap.rb [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+SitemapGenerator::Sitemap.create do
+  Seek::Util.searchable_types.each do |type|
+    add  polymorphic_path(type), lastmod: type.maximum(:updated_at), changefreq: 'daily', priority: 0.7
+  end
+end
+
+Seek::Util.searchable_types.each do |type|
+  SitemapGenerator::Sitemap.create(filename: type.table_name, include_root: false) do
+    type.authorized_for('view', nil).find_all do |obj|
+      add polymorphic_path(obj), lastmod: type.maximum(:updated_at), changefreq: 'daily', priority: 0.7
```
Comment (fbacall) [inline config/sitemap.rb:16]: `lastmod` for the object should be its own `updated_at`: `obj.updated_at`

Comment (fherreazcue) [reply config/sitemap.rb]: Fixed in [4d68328](https://github.com/seek4science/seek/pull/1578/commits/4d68328bdbcde9a2cdf250893d9b498f8c70d9b2).

**Review by stuzart — APPROVED** [review]
