### PR TITLE
Fix sample API (and other actions) not being available when using OAuth

### LINKED ISSUE #1966: Samples API not accessible via OAuth authentication
...Due to missing `api_actions` declaration in controller.

### PR DESCRIPTION
**Pull request by fbacall**
Also changes API integration tests to authenticate via OAuth

Fixes #1966

### CODE REVIEW

File: test/unit/helpers/dynamic_table_helper_test.rb [hunk 1]
```diff
@@ -48,6 +48,15 @@ class DynamicTableHelperTest < ActionView::TestCase
...
 
+      unless (dt[:rows][0].any? { |x| x == '' }) || (dt[:rows][1].any? { |x| x == '' }) || (dt[:rows][2].any? { |x| x == '' })
+        puts
+        puts "Flaky test debug:"
+        puts
+        puts dt.inspect
+        puts
+        pp study.sample_types
+      end
+
```
Comment (stuzart) [inline test/unit/helpers/dynamic_table_helper_test.rb:59]: some debugging puts code

**Review by stuzart — CHANGES_REQUESTED** [review]
just some debugging code left behind

File: test/unit/helpers/dynamic_table_helper_test.rb (hunk 1 above)
Comment (fbacall) [reply test/unit/helpers/dynamic_table_helper_test.rb:59]: I was going to leave that in to try and figure out why that test randomly fails sometimes

**Review by stuzart — APPROVED** [review]
