### PR TITLE
Issue 1977 query by est fix reg samples

### LINKED ISSUE #1977: Querying by EST - registered (input) samples does not work
Querying by Experiment Sample Template does not return any samples when a registered (input) sample is used as a query.

Browsing samples by Experiment Sample Template is possible by querying according to different attributes, including String, Output sample, CV, … However, whenever an input sample attribute is selected, the search returns zero samples. 

Ps: Searching with wildcards within ‘Query by Experiment Sample Template’ also does not work. It does work for the ‘normal’ search function ([Issue #1827](https://github.com/seek4science/seek/issues/1827))

Screenshots
Query for samples using the assay sample template returns 176 samples, showing one sample using input sample name “ss_TMDsel_0001”:
image

Filtering samples using the assay sample template using input “ss_TMDsel_0001” (0 samples):
image

Filtering samples using the assay EST using advanced filtering (Study sample; output name = “ss_TMDsel_0001” (1 sample):
image

Filtering samples using the assay EST using advanced filtering (Study sample; input name = “s_TMDsel_0001” (0 samples):
image

Filtering samples using the assay EST using advanced filtering (Study source; output name = “s_TMDsel_0001” (1 sample):
image

Details can also be found in the following [Google Document](https://docs.google.com/document/d/1507RWawIHXMHo9YcJd38aXWJRf2YtGLxWRqDW8Ri47E/edit)

### PR DESCRIPTION
**Pull request by kdp-cloud**
Fixes #1977 

- Querying samples by attributes that are not of type string, like SEEK samples and CV lists, is now possible.
- The query matches are now not case-sensitive anymore

### CODE REVIEW

File: app/controllers/samples_controller.rb [hunk 1]
```diff
@@ -318,16 +332,34 @@ def find_index_assets
...
+  # @param options [Hash] the options for filtering
+  # @option options [Integer] :template_id the ID of the template to filter by
+  # @option options [String] :attribute_value the value of the attribute to filter by
+  # @option options [Integer] :attribute_id the ID of the attribute to filter by
+  # @param template_attribute_title [String] the title of the template attribute to filter by
+  # @return [Array<Sample>] the filtered list of samples
+  def filter_linked_samples(samples, link, options, template_attribute)
+    template_attribute_title = template_attribute&.title
     samples.select do |s|
       s.send(link).any? do |x|
```
Comment (stuzart) [inline app/controllers/samples_controller.rb:348]: i think this is potentially dangerous, maybe not now but could be due to an error in the future. Just needs to check the `link` is in a list of allowed method calls, or have another way of specifying which method is called.

**Review by stuzart — CHANGES_REQUESTED** [review]

File: app/controllers/samples_controller.rb (hunk 1 above)
Comment (kdp-cloud) [reply app/controllers/samples_controller.rb:350]: Indeed! makes sense.
Now it will raise an error if `link` is not either `:linked_samples` or `:linking_samples`.

**Review by stuzart — APPROVED** [review]
