### PR TITLE
Issue 1977 query by est

### LINKED ISSUE #1977: Querying by EST - registered (input) samples does not work
Querying by Experiment Sample Template does not return any samples when a registered (input) sample is used as a query.

Browsing samples by Experiment Sample Template is possible by querying according to different attributes, including String, Output sample, CV, … However, whenever an input sample attribute is selected, the search returns zero samples. 

Ps: Searching with wildcards within ‘Query by Experiment Sample Template’ also does not work. It does work for the ‘normal’ search function ([Issue #1827](https://github.com/seek4science/seek/issues/1827))

Screenshots
Query for samples using the assay sample template returns 176 samples, showing one sample using input sample name “ss_TMDsel_0001”:
image

Filtering samples using the assay sample template using input “ss_TMDsel_0001” (0 samples):
image

Filtering samples using the assay EST using advanced filtering (Study sample; output name = “ss_TMDsel_0001” (1 sample):
image

Filtering samples using the assay EST using advanced filtering (Study sample; input name = “s_TMDsel_0001” (0 samples):
image

Filtering samples using the assay EST using advanced filtering (Study source; output name = “s_TMDsel_0001” (1 sample):
image

Details can also be found in the following [Google Document](https://docs.google.com/document/d/1507RWawIHXMHo9YcJd38aXWJRf2YtGLxWRqDW8Ri47E/edit)

### PR DESCRIPTION
**Pull request by kdp-cloud**
- Fixes querying for booleans and numeric types
- Closes #1977

### CODE REVIEW

File: app/controllers/samples_controller.rb [hunk 1]
```diff
@@ -343,21 +330,14 @@ def find_index_assets
   # @param template_attribute_title [String] the title of the template attribute to filter by
   # @return [Array<Sample>] the filtered list of samples
   def filter_linked_samples(samples, link, options, template_attribute)
-    raise ArgumentError, "Invalid linking method provided. '#{link.to_s}' is not allowed!" unless %i[linked_samples linking_samples].include? link
+    unless %i[linked_samples linking_samples].include? link
+      raise ArgumentError, "Invalid linking method provided. '#{link}' is not allowed!"
+    end
 
-    template_attribute_title = template_attribute&.title
+    # template_attribute_title = template_attribute&.title
```
Comment (stuzart) [inline app/controllers/samples_controller.rb:337]: looks like this can just be removed

File: test/functional/samples_controller_test.rb [hunk 2]
```diff
@@ -7,6 +7,15 @@ class SamplesControllerTest < ActionController::TestCase
...
   include GeneralAuthorizationTestCases
 
+  def setup
+    @source_characteristic_isa_tag = FactoryBot.create(:source_characteristic_isa_tag)
+    @sample_characteristic_isa_tag = FactoryBot.create(:sample_characteristic_isa_tag)
+    @other_material_characteristic_isa_tag = FactoryBot.create(:other_material_characteristic_isa_tag)
+    Seek::Samples::BaseType::ALL_TYPES.each do |type|
+      FactoryBot.create(:string_sample_attribute_type, title: "#{type} attibute type", base_type: type)
+    end
+  end
```
Comment (stuzart) [inline test/functional/samples_controller_test.rb:17]: I don't think we need this for every test, and will create some overhead. Best to put into a method for the tests that require it.

**Review by stuzart — CHANGES_REQUESTED** [review]
