### PR TITLE
Versioning fixes

### LINKED ISSUE #1229: Can't change version visibility for `Git::Version`s
It's possible in the model, but there's no UI or controller action to do it.

### PR DESCRIPTION
**Pull request by fbacall**
Some method renaming in versioning systems to prevent confusion.

- Methods prefixed with `standard_` always refer to `ExplicitVersioning` versions.
- Methods prefixed with `git_` always refer to git versions.
- Non-prefixed methods will switch between the 2 systems: https://github.com/seek4science/seek/blob/fix-versioning-ambiguity/lib/git/versioning_compatibility.rb
 
Fixes #1229 and #1470

Also fixes some types missing from `Person#contributed_items`.

### CODE REVIEW

File: config/routes.rb [hunk 1]
```diff
@@ -131,6 +131,8 @@
         patch 'blob/*path' => 'git#move_file', as: :git_move_file
         get 'freeze' => 'git#freeze_preview', as: :git_freeze_preview
         post 'freeze' => 'git#freeze', as: :git_freeze
+        patch '' => 'git#update', as: :git_update_version
+        #delete '' => 'git#destroy', as: :git_destroy_version
```
Comment (stuzart) [inline config/routes.rb:135]: is this intended to be commented out, and if so could just be removed ?

**Review by stuzart — CHANGES_REQUESTED** [review]
just something commented out to double check

File: config/routes.rb (hunk 1 above)
Comment (fbacall) [reply config/routes.rb:135]: Yeah it can probably be removed. I started looking into how removing versions works for non-git versioned things but wasn't sure if we are supporting that feature now that you can just hide versions.

**Review by stuzart — APPROVED** [review]

**Comment by stuzart** [comment]
Although I approved it, I've just noticed the unit tests are failing.
